### ISSUE TITLE
1:1 Intro Calls

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#111]
Book Openscapes Intro Calls (aka 1:1's )

- [x] create Google Calendar "appointment slots" in OpenscapesCohorts calendar with 30-min meeting segments 
- [x] in Welcome email, invite folks to book an intro call that should include their team, if they are participating with one
- [x] day before intro calls, create one doc per meeting from template
- [x] conduct intro calls

**Comment by jules32** [comment]
thanks for making the 1:1 docs! I've added zoom info to the calendar invites. Looking forward to next week!
