### ISSUE TITLE
Cohort planning [ 2023-epa ]

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#131]
For EPA, docs are generally created by us in Google Workspace, downloaded in Word or Excel, and uploaded and then maintained in MS Sharepoint. After Cohort, we'll copy finalized docs & sheets into Openscapes Google Workspace for our records

- [x]  Add Cohort to [`OpenscapesChampionsCohortRegistry`](https://docs.google.com/spreadsheets/d/1Ys9KiTXXmZ_laBoCV2QWEm7AcnGSVQaXvm2xpi4XTSc/) Google sheet as soon as dates are set
- [x] Create [`Openscapes-CohortPlanningDoc [ 2023-epa ]`](https://usepa.sharepoint.com/:w:/r/sites/CEMMCODSPilot-Private-ContractItems/Shared%20Documents/Private-Contract%20Items/Openscapes-CohortPlanningDoc%20%5B%202023-epa%20%5D.docx?d=wfa3df3b957f340d2b98dbbfe802c5117&csf=1&web=1&e=z4kQGU) Google doc (copy from recent doc); for EPA this is in MS Sharepoint
- [x] Create [`CohortCalendaring [ 2023-epa ]`](https://usepa.sharepoint.com/:x:/r/sites/CEMMCODSPilot-Private-ContractItems/Shared%20Documents/Private-Contract%20Items/CohortCalendaring%20%5B%202023-epa%20%5D.xlsx?d=w3a07197e3efe48ba888218ebf3edcb77&csf=1&web=1&e=qAsbQM) Google sheet (copy from recent doc); for EPA this is in MS Sharepoint
- [x] populate CohortCalendaring [ 2023-epa ] with dates, session topics, guests etc
- [x] add to [Openscapes Events](https://openscapes.github.io/events/)

**Comment by stefaniebutland** [comment]
@jules32 working on the checklist above and aiming to harmonize dates and topics 
- [ ] set coworking time
  - Could we set EPA coworking for 1-hr slots same as Cohort Calls - Wednesdays 10-11am PT? If you're available + Gayle & Jeff (since we don't poll participants for a time)
- [ ] please check `CohortCalendaring [ 2023-epa ]` for accuracy
  - I'll screenshare/ cowork to how to clean up the sheet formatting
- [ ] We need to complete `OpenscapesChampionsCohortRegistry - call_metadata`

Is it ok if I link to our files from these issues?

**Comment by jules32** [comment]
Hi @stefaniebutland 

Yes, please link to these files from here, it will help identify Sharepoint and GDocs :). 

- Wednesdays at the Cohort Call slot won't work for me, let's find another time with Jeff and Gayle
- I've made a few updates to [CohortCalendaring [ 2023-epa ]](https://docs.google.com/spreadsheets/d/1BPn4jF7GAmZ_7H-ONNYu_ClD71xTInR1WDRdhLYfFyQ/edit#gid=1662616975)
- I've completed the [call_metadata](https://docs.google.com/spreadsheets/d/1Ys9KiTXXmZ_laBoCV2QWEm7AcnGSVQaXvm2xpi4XTSc/edit#gid=942365997) for what we need I believe

**Comment by stefaniebutland** [comment]
Awesome thanks. 

I've moved files to Sharepoint (links in checklist at top), adding notes to our Google Workspace Docs to indicate they are not maintained, and show their locations in Sharepoint. I've added item to the [Wrap up issue template](https://github.com/Openscapes/cohort-planning/blob/main/.github/ISSUE_TEMPLATE/wrap-up.md) to remind us to copy final docs to our Google Workspace
