### ISSUE TITLE
Cohort tech setup [ 2023-epa ]

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#132]
## For Cohort Planning Team (Stef, Julie)

These tasks are described in the [Approach Guide - Cohort tech setup](https://openscapes.github.io/approach-guide/champions/pre-cohort-tech.html)

For our 2023-EPA Cohort we will use Microsoft Sharepoint to manage and access folders and files that we usually manage in Google Drive.  Our workflow will be to create Agendas with kyber as usual, edit content and formatting in Google docs, then download Google doc Agenda to MS Word and upload that to the Cohort Sharepoint folder.

- [x] invite co-leads/assists to Google / Outlook Calendar Cohort Calls (Gayle)

GitHub:
-   [x] create GitHub repo for cohort with cohort name (example: github.com/openscapes/2022-noaa-sefsc-summer)
-   [x] Write Cohort info on the README (kyber)
    - known [error running init_repo #36](https://github.com/Openscapes/kyber/issues/36) so doing this manually
-   [x] Add our Code of Conduct (kyber)
-   [x] add MS Sharepoint link (created below) to README
-   [x] Make it a website: Settings \> Pages \> Branch: main, dir: root; add website link to repo About
-   [x] Invite co-leads/assists to GitHub repo with Maintainer permissions

Google Folder / Sharepoint:
-   [x] create Google Folder for participants (example: `Openscapes_CohortCalls [ 2022-noaa-sefsc-summer ]`)
-   [x] add co-leads/assists to Google Folder for participants
    - Gayle and Jeff have access to the Sharepoint / Teams folder

**Comment by stefaniebutland** [comment]
Woohoo! 
- https://github.com/Openscapes/2023-epa
- https://openscapes.github.io/2023-epa/

I don't see at GitHub acct for Gayle, but that's ok.

@jules32 Please check that the setup is 👍🏼 and we can close this issue!

**Comment by jules32** [comment]
This looks great! 🎉
