### ISSUE TITLE
Copy slides to Openscapes Google Workspace

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#134]
Google Slides - copy to openscapes account, update links in series (don’t delete originals, but add note that they’re not updated past 2022 and provide new link)

**Comment by stefaniebutland** [comment]
Done, including kyber updates. Let's double check before closing the issue @jules32

**Comment by jules32** [comment]
Thanks Stef! Yes following the NASA Champions Cohort we can close. Thanks!

**Comment by stefaniebutland** [comment]
moving issue to TODO status
