### ISSUE TITLE
Create Call Agendas 1-3 NASA Openscapes

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#148]

**Comment by jules32** [comment]
Hi Stef, By Wednesday Mar 8 could you please create Calls 1-3 Agendas so Erin and you can plan refocus for curriculum cloud with the NASA Mentors during their Mar 8 cohort call. Calls 1-3 are slightly different than core: 

https://nasa-openscapes.github.io/2023-nasa-champions/

**Comment by jules32** [comment]
Here is the folder for the agendas: https://drive.google.com/drive/folders/1hAge8k2z9OvXB7c2nEg_BQA36Fc1cRLk?usp=sharing

**Comment by stefaniebutland** [comment]
thanks @jules32. Agendas 1-3 will be in that folder & formatted by end of day Tues Mar 7.

**Comment by stefaniebutland** [comment]
Agendas in folder & pinged Erin.
