### ISSUE TITLE
Cohort planning [ 2023-nasa-champions ]

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#149]
- [x] Add Cohort to `OpenscapesChampionsCohortRegistry` Google sheet as soon as dates are set
- [ ] ~Create `Openscapes-CohortPlanningDoc [ 2023-nasa-champions ]` Google doc (copy from recent doc)~
- [x] Create `CohortCalendaring [ 2023-nasa-champions ]` Google sheet (copy from recent doc)
- [x] populate `CohortCalendaring [ 2023-nasa-champions ]` with dates, session topics, guests etc
- [x] add to [Openscapes Events](https://openscapes.github.io/events/) 

Link to the relevant docs from this issue, once they're created.

**Comment by jules32** [comment]
@stefaniebutland I've created the [CohortCalendering spreadsheet](https://docs.google.com/spreadsheets/d/1T09rz75x7pKSE1UesH2gy2HCe7EnevhZ7bKFYXjT6dU/edit#gid=0). Could you populate/update it this week and I'll pick things up as I invite the guest teachers? Thank you!

**Comment by stefaniebutland** [comment]
will do today!

**Comment by stefaniebutland** [comment]
It looks like you've already populated it @jules32. Let me know if there's something further to add

**Comment by jules32** [comment]
Yes we're all set here, thanks!
