### ISSUE TITLE
Intro Calls (aka 1:1's ) [ 2023-nasa-champions ]

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#152]
Book Openscapes Intro Calls (aka 1:1's )

Described in Approach Guide - [Pre-cohort engagement](https://openscapes.github.io/approach-guide/champions/pre-cohort-engage.html#intro-calls).

- [x] create Google Calendar "appointment slots" in OpenscapesCohorts calendar with 30-min meeting segments 
- [x] in Welcome email, invite folks to book an intro call that should include their team, if they are participating with one
- [x] day before intro calls, create one doc per meeting from template
- [x] conduct intro calls

**Comment by jules32** [comment]
Last two scheduled Friday and Monday
