### ISSUE TITLE
Prepare final Cohort Call [ 2023-nasa-champions ]

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#161]
- [x] Create Agenda (kyber)
- [x] Invite participants / teams to sign up in Agenda to present their Pathway
- [ ] create Survey - copy most recent and save; in OpenscapesMain > OpenscapesMetrics > Surveys
  - [ ] Add link to Agenda
- [x] Review roles and timing

**Comment by stefaniebutland** [comment]
add this to Call 5 Closing:

You can add this to your resume: Professional Development: Openscapes Champions Lesson Series, April - June, 2023 https://doi.org/10.5281/zenodo.7407246 

...thinking we (I) need to add Earthdata Cloud Clinic to Lesson Series and make another GitHub Release to bump the DOI in Zenodo because the content at current DOI does not include new NASA content

**Comment by jules32** [comment]
Also add to Next Steps: 

Next steps and opportunities
- Cookbook walk-through (Mentors screenshare, 5 mins)
- IceSat-2 Hackweek 2023 - 7-11 August, Seattle https://icesat-2.hackweek.io/
- Carpentries

**Comment by stefaniebutland** [comment]
@jules32 Call 5 Agenda ready for you 🤝
