### ISSUE TITLE
Summary blog post [ 2023-nasa-champions ]: Aug 1

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#169]
- [x] select one project or pathway element from each team
- [x] draft post
- [x] publish & tweet / toot post

**Comment by stefaniebutland** [comment]
Stef will start post in debriefs doc then ping Julie & Erin

**Comment by jules32** [comment]
I will help draft after ESIP; @erinmr do you have time before then?

**Comment by erinmr** [comment]
I will get it started and we can finalize at the end of July.

**Comment by stefaniebutland** [comment]
Post is started in DebriefsDigests [ 2023-nasa-champions ]: Summary Blog Post

**Comment by jules32** [comment]
Awesome, thank you both!

**Comment by erinmr** [comment]
Hi @jules32 and @stefaniebutland - Here is a start at the Cohort blog -> https://docs.google.com/document/d/1DnzIv2cVhOgmbiU4EGGWE6Lb8TlgcroP4V7tU8OhfQc/edit Edits welcome!

**Comment by stefaniebutland** [comment]
A great read. I've made a few language/capitalization edits, linked to Ziheng's tut in the cookbook

**Comment by erinmr** [comment]
thanks!

**Comment by jules32** [comment]
Awesome blog post @erinmr ! I just made some light additions, and it's ready to go. 

I've asked Jennifer about cross-posting on the NASA blog and @stefaniebutland can get it ready to publish on August 1 - thanks Stef!

**Comment by stefaniebutland** [comment]
published https://openscapes.org/blog/2023-08-01-nasa-champions/
and tooted

**Comment by stefaniebutland** [comment]
@jules32 I'll leave this open till NASA cross post is resolved.
