### ISSUE TITLE
Digests - move Digests out of Issues into Discussions

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#171]
Erin did this for NASA Cohort Calls. Makes sense. What do you think @jules32 

- [ ] Move NASA Call 2 Digest to Discussion, delete Call 1 Issue (cause it's in Discussion)

HOLD - Update Documentation
    - Issue Template
    - Approach Guide section
    - kyber REAMDE.Rmd source ("Cohort Call Digests are posted as issues in this repo." if it's in there; maybe we just added manually before

**Comment by jules32** [comment]
I think let's continue with Discussions for NASA Champions now and we can see how we like it. Then, as a Phase 2 when we repeat it we can update the documentation and templates. But I think we can hold on documentation now

**Comment by stefaniebutland** [comment]
done
