### ISSUE TITLE
Cohort planning [ 2023-fred-hutch ]

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#172]
- [x] Add Cohort to `OpenscapesChampionsCohortRegistry` Google sheet as soon as dates are set
- [x] Create `Openscapes-CohortPlanningDoc [ year-cohort-name ]` Google doc (copy from recent doc)
- [x] Create `CohortCalendaring [ year-cohort-name ]` Google sheet (copy from recent doc)
- [x] populate `CohortCalendaring [ year-cohort-name ]` with dates, session topics, guests etc
- [x] add to [Openscapes Events](https://openscapes.github.io/events/) 

Link to the relevant docs from this issue, once they're created.

**Comment by jules32** [comment]
Here is the draft events page: https://openscapes.org/events/2023-08-29-fred-hutch/ (here’s [the .qmd](https://github.com/Openscapes/website-new/blob/main/events/2023-08-29-fred-hutch/index.qmd), it’s a draft so not visible on the public listing page).

- [ ] TODO: Before we make it live I’ll update with the final date-times; I picked Option 1 as a default.

**Comment by jules32** [comment]
Option 1 chosen, published to events page and Sean is sharing with PIs

**Comment by stefaniebutland** [comment]
@jules32 CohortCalendaring sheet is done. I left Coworking and Mentors Seaside Chats dates blank till these are confirmed. We can close this issue once we agree all the parts are in place 😁

**Comment by jules32** [comment]
Thank you Stef! I've just sent a few calendar invites for Monday Mentor Huddles (Seaside Chats) that we can fill in once confirmed.
