### ISSUE TITLE
Cohort tech setup [ 2023-fred-hutch ] - Aug 23

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#173]
## For Cohort Planning Team (Stef, Julie)

These tasks are described in the [Approach Guide - Cohort tech setup](https://openscapes.github.io/approach-guide/champions/pre-cohort-tech.html)

- [x] invite co-leads/assists to Google Calendar Cohort Calls

GitHub:
-   [x] create GitHub repo for cohort with cohort name (example: github.com/openscapes/2022-noaa-sefsc-summer)
-   [x] Write Cohort info on the README (kyber)
-   [x] Add our Code of Conduct (kyber)
-   [x] add Google Folder link (created below) to README
-   [x] Make it a website: Settings \> Pages \> Branch: main, dir: root; add website link to repo About
-   [x] Invite co-leads/assists to GitHub repo with Maintainer permissions

Google Folder:
-   [x] create Google Folder for participants (example: `Openscapes_CohortCalls [ 2022-noaa-sefsc-summer ]`)
-   [x] add co-leads/assists to Google Folder for participants

**Comment by stefaniebutland** [comment]
created [Google folder](https://drive.google.com/drive/folders/1i-ZZRMvEHDwQ5vJZpX_P4ycqOTwAKnyM?usp=drive_link) with restricted access. We'll add people individually

**Comment by jules32** [comment]
Thanks Stef! I moved the [Google folder](https://drive.google.com/drive/folders/1i-ZZRMvEHDwQ5vJZpX_P4ycqOTwAKnyM?usp=drive_link) to the ChampionsCohorts main folder and created the ParticipantsList
