### ISSUE TITLE
Intro Calls (aka 1:1's ) [ 2023-fred-hutch ] - Aug 22

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#174]
Book Openscapes Intro Calls (aka 1:1's )

Described in Approach Guide - [Pre-cohort engagement](https://openscapes.github.io/approach-guide/champions/pre-cohort-engage.html#intro-calls).

- [ ] create Google Calendar "appointment slots" in OpenscapesCohorts calendar with 30-min meeting segments 
- [ ] in Welcome email, invite folks to book an intro call that should include their team, if they are participating with one
- [ ] day before intro calls, create one doc per meeting from template
- [ ] conduct intro calls

**Comment by jules32** [comment]
Closing; with Fred Hutch we did an "Ask Us Anything" Aug 22 in place of 1:1's
