### ISSUE TITLE
Prepare final Cohort Call 5 [ 2023-fred-hutch ]

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#180]
- [x] Create Agenda (kyber)
- [x] add blank Agenda to this Google folder [OpenscapesChampions_CohortCalls [ public ]](https://drive.google.com/drive/folders/1Iq8tj81TSfr-RstphVTZWoz783xpJMOb?usp=drive_link)
- [x] Invite participants / teams to sign up in Agenda to present their Pathway
- [x] create Survey - copy most recent and save; in OpenscapesMain > OpenscapesMetrics > Surveys
  - [x] Add link to Agenda
- [x] Review roles and timing

**Comment by stefaniebutland** [comment]
Stef coordinate with Sean about preparing to screenshare (& record) one or two DaSL workflow things after everyone has presented Pathways

**Comment by stefaniebutland** [comment]
@jules32 Call 5 Agenda is ready for your review. I've DM'd co-leads about Pathways "presentations", prompt for Next Steps. 
I've got skeleton slides for my kyber pathway in the Cohort Pathways folder

**Comment by jules32** [comment]
I reviewed, it looks great Stef. I'm excited for this, you'll (all) do so awesome!

**Comment by stefaniebutland** [comment]
Thanks Julie! I'll leave this open till Sean and Monica and I have a plan for Pathway presentations and next steps

**Comment by stefaniebutland** [comment]
1. @seankross ! @monicagerber! We’re hatching [our plan for Call 5](https://docs.google.com/document/d/1lyb_yASC4eIt7YIIa9aJ99Z_HPB7NhzOEJ87vFs_wx4/edit)(Oct 31) where we’ve asked each team to present their “Pathway” (We've referred to Pathways steps as tasks in Closing section of Call Agendas).  These are 3 min presentation + 3 min Q&A. I’ll start by sharing my Pathway - e.g. using kyber for agendas then have ppl from 3 teams. With only 3 teams we have some leeway and want you to get the most of it for DaSL so ...

- **Sean** is there a thing you would like to “screenshare and tell”? e.g. something you want to follow up from a HouseCall or from Call 4 where you respond to a question that might be common across the cohort? We'll be recording, so could give you a clip to reuse/share as a DaSL resource. To push it a step further, I wonder if someone in the Cohort would be willing to screenshare a question-thing and you talk them through a solution? again, so you could reuse.

- **Monica**, is there something you or Sita might share from your DaSL resource connection in Call 3? 

2. After all presentations, right before Closing, we take 10 mins for silent journaling & discussion of Next Steps. Would you like to edit the current prompt in any way to elicit what is most helpful for you? Please feel free to [edit directly in the doc](https://docs.google.com/document/d/1lyb_yASC4eIt7YIIa9aJ99Z_HPB7NhzOEJ87vFs_wx4/edit#heading=h.20vsxmd7w642), or reply here and I'll add.

> We want to help you all maintain momentum. What are your needs? What kind of support do you need from your team, DaSL, or elsewhere? Let’s silent journal and get your thoughts out; the objective isn’t to get a poll, it’s about your ideas, needs, and also how you feel about it all.


3. Sean is there something you'd like to say during [Closing](https://docs.google.com/document/d/1lyb_yASC4eIt7YIIa9aJ99Z_HPB7NhzOEJ87vFs_wx4/edit#heading=h.snbka66ujhiw)?

**Comment by monicagerber** [comment]
Hi Stef! The plan looks great. Sita and I haven't been able to meet yet, so I don't have anything to share from that. I could "screen share and tell" how DaSL is adopting the Seaside chats/co-working sessions. 

The current silent journaling prompt looks good to me.

**Comment by seankross** [comment]
Hey Stef, the data house calls generated from Call 4 will not have happened by the time Call 5 rolls around. 

>I wonder if someone in the Cohort would be willing to screenshare a question-thing and you talk them through a solution?

I would be happy to do that, but I can come up with something as a backup too, likely about the specifics of using GitHub at Fred Hutch.
