### ISSUE TITLE
Summary blog post [ 2023-fred-hutch ] - pub Nov 14, draft Nov 07

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#187]
- [x] select one project or pathway element from each team
- [x] draft post
- [x] publish & tweet / toot post

**Comment by stefaniebutland** [comment]
“Tell your roommate moments” like posit::conf sharing back to Julie.
Near end, what was different about this cohort?
Julie’s back from vacation in plenty of time to review

**Comment by stefaniebutland** [comment]
@jules32 *rough* draft PR for wrap up post: https://github.com/Openscapes/website-new/pull/69

For now, each team/lab text is not good - just copied what I had in Call 5 digest. It would help me a lot if you took a quick look and noted anything I might highlight. I haven't yet rewatched the video to do my next round of draft.

**Comment by jules32** [comment]
Hi @stefaniebutland ! It's a great start :). I added to your PR some suggested text for the intro. I think that the starter text for teams/labs from the digest is great, and fine to reuse and include all of it. It could use another run through to smooth over but nice to have all those details included.

**Comment by stefaniebutland** [comment]
published https://openscapes.org/blog/2023-12-04-fred-hutch/
