### ISSUE TITLE
Better science slides: Stef's story. Aug 29

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#188]

**Comment by jules32** [comment]
@stefaniebutland , here are the [Better Science slides](https://docs.google.com/presentation/d/1tE3pQ2ObNU68iG4uTIlMuSN4dguvn-cOvwtoM-c9L-w/edit#slide=id.g275324a57db_0_16). 

**Total: 15 mins** (I was wrong when I said 20)

**Focus:** share your story in place of slides 2-6

**Comment by stefaniebutland** [comment]
done! Opened issue to add video to YouTube https://github.com/Openscapes/approach-guide/issues/75
