### ISSUE TITLE
01 Cohort planning docs & sheets [ 2024-epa ]

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#190]
- [x] Add Cohort to `OpenscapesChampionsCohortRegistry` Google sheet as soon as dates are set
- [x] Create `Openscapes-CohortPlanningDoc [ 2024-epa ]` Google doc (copy from recent doc)
- [x] Create `CohortCalendaring [ 2024-epa  ]` Google sheet (copy from recent doc)
- [x] populate `CohortCalendaring [ 2024-epa  ]` with dates, session topics, guests etc
- [x] add to [Openscapes Events](https://openscapes.org/events) 

Link to the relevant docs from this issue (only if they're public?), once they're created.

**Comment by stefaniebutland** [comment]
@jules32 please review `CohortCalendaring [ 2024-epa ]` and tag me to move it to Teams. I can invite speakers if you like.

**Comment by jules32** [comment]
reviewed together, thanks Stef!

**Comment by stefaniebutland** [comment]
Aneese Williams will give Call 3 Data Strategies
Jeff can give Call 1 Better Science; he's open to someone else doing it, but yay!

Copied `CohortCalendaring [ 2024-epa  ]` as xlsx to Teams for visibility for EAP. Future edits will be made there
