### ISSUE TITLE
Prepare final Cohort Call 5 [ 2024-epa ]

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#205]
- [x] Create Agenda (kyber)
- [x] Invite participants / teams to sign up in Agenda to present their Pathway
- [x] create Survey - copy most recent and save; in OpenscapesMain > OpenscapesMetrics > Surveys
  - [x] Add link to Agenda
- [x] Review roles and timing

**Comment by stefaniebutland** [comment]
Created [Certificates with Kyber](https://openscapes.github.io/kyber/articles/create-certificates.html). Temp stored in our Cohort Google Folder; will move to Teams prior to Call 5

**Comment by stefaniebutland** [comment]
@jules32 Call 5 Agenda now in Teams for your review/edits.

- Roles: I have added you for Followups (re: new paper), Next steps, Closing. 
- Survey linked in Closing and I'll add to Digest. 
- I'll review my Pathway slides and link before the call.

**Comment by jules32** [comment]
This all looks great Stef! Would you prefer to share Followups, since you're a co-author? That might have a nice flow. Otherwise, all looks great. thank you!

**Comment by stefaniebutland** [comment]
I've emailed Farnaz & cc'd you. Good idea.
Happy to share Followup on editorial

**Comment by stefaniebutland** [comment]
demo idea for our back pocket: 
- GitHub Projects for more visible planning and fewer emails. Could demo [NASA Openscapes MainPlanning](https://github.com/orgs/NASA-Openscapes/projects/7/views/3) with Roadmap view; link to Comm Call as resource

**Comment by stefaniebutland** [comment]
also, Quarto manuscript example. Not applicable to many, but a nice example that we could add to agenda as a resource. Someone noted in Call 4 Reflections wanting to do this

from @alex-koiter Brandon U in Manitoba, who on his sabbatical decided to start / learn doing manuscripts in Quarto on GitHub 🥳 

> here is the repo with the quarto manuscript that has [was already] published https://github.com/alex-koiter/sampling-design-manuscript

> Here is the repo that i used quarto manuscripts from the very start and is currently under peer review https://github.com/alex-koiter/riparian-grazing-manuscript

**Comment by stefaniebutland** [comment]
from @jhollist
> I wonder if the GitHub side of things was a bit much (i.e. GitHub pages, actions to automatically render, etc.).  Maybe a non-Web page demo of just quarto, with manual render, in RStudio would be good.

> Could be slides, or maybe an example analysis/notebook kinda format that highlights the mixing of Text and Code for literate programming?

**Comment by stefaniebutland** [comment]
from @farnazn 

> I think it would be useful for everyone to know where to start if they want to write manuscripts in quarto. Someone has mentioned it in the silent journaling too. I agree with Jeff; a demo of quarto in RStudio would be good. My concern with demoing something like this is that it is very slow to render on a Teams call.

> Quarto guide has a great tutorial for authoring manuscripts ([Quarto – Authoring Manuscripts](https://quarto.org/docs/manuscripts/authoring/rstudio.html)) which I think would be a good starting point and resource for everyone- this particular tutorial but the guide itself in general too.

**Comment by jules32** [comment]
Hi! +1 Walking through the [Quarto – Authoring Manuscripts](https://quarto.org/docs/manuscripts/authoring/rstudio.html) tutorial would be a good demo; we could stop at "Visual Editor" and let people continue from there. 

Great if Farnaz/Stef would like to walk though; I've cloned the accompanying template repository and happy to demo if needed.

Excited!

**Comment by jhollist** [comment]
I do think showing the visual editor is a good idea.  The code look and feel or source can turn people off.  Knowing that they can get a word processor ish feel has helped some folks I've worked with make the switch.

Like this idea!

---------------------------------------------------------------------
Jeffrey W. Hollister, Ph.D.
Ecologist, Monitoring and Assessment Branch
USEPA Office of Research and Development
27 Tarzwell Drive
Narragansett, RI 02882
Cell: 401 556 4087
Office: 401 782 9655

Pronouns: he/him/his Learn More<https://pronouns.org/>
---------------------------------------------------------------------
Note:  I may email beyond regular working hours.  I do NOT expect a response outside of your normal working hours. Thanks!

**Comment by stefaniebutland** [comment]
> showing the visual editor is a good idea.

great point
@farnazn would you feel comfortable walking through this? Jeff already had his turn presenting :-)

**Comment by farnazn** [comment]
Hey @stefaniebutland, Not really :( I don't have enough time to prep for it before the meeting.

**Comment by stefaniebutland** [comment]
No worries. Realized I might have sounded like we're pressuring. Thank you for a clear "no"!

**Comment by farnazn** [comment]
@stefaniebutland No worries at all and in fact I am grateful for the opportunity. I am just bummed I did not have time to prepare and actually do it.

**Comment by stefaniebutland** [comment]
Successful final Call!! Moving on to wrap up issue
