### ISSUE TITLE
DRAFT 04 Cohort Call Digest [ 2021-fdd ]

### ISSUE THREAD

**Issue by AHolder1** [Openscapes/cohort-planning#27]
- [x] Julie initial review
- [x] Julie final check-off

---

Hi All,

Thanks for a great fourth session last Friday. Thank you to Gavin, Andy, and Rachel for making this FDD cohort happen, and big thanks to all of the teams for contributions to conversations and notes throughout this Openscapes process. We loved hearing about your Pathways last week and are looking forward to continued conversations and momentum around how the FDD community can do better science in less time - for future you, your teams, and your collaborators! 

A few things to wrap up:

1. **[Openscapes survey](https://docs.google.com/forms/d/e/1FAIpQLSf2Ybv8paycBEODve--S3HwYkvPM3d-vGf_s1xStiuLG5Px5g/viewform?usp=sf_link)** - Openscapes improves with each cohort based on candid feedback. Please provide feedback by by Friday Nov 12

2. **Continuing Cohort Calls** - We'll send calendar invites for our every-two-week calls, with the short-term plan of alternating these times as co-working and more scheduled share-outs. We'll invite the [NOAA NMFS Cohort](https://openscapes.github.io/2021-noaa-nmfs) as well; they've just finished their cohort too and we through we could combine forces and see what next steps emerge. Feb 4 can be our 3-month check-in to reassess. 

3. **Blog post** - we'll draft this in our [CohortCalls folder](https://drive.google.com/drive/u/2/folders/1Xx-G_9s6DGz4JduYQblJNuMMFaPgU7sb) later this week; we invite you to add comments or suggestions if you’re interested. 

4. **Snail mail!** Please Slack/email an address for your team to Julie (lowndes@nceas.ucsb.edu) so we can send stickers!

We are so grateful for your thoughtful engagement and impressed with your progress and pathway plans. We hope you continue to iterate your Seaside Chats with your research groups and we are happy to meet with your research groups during a Seaside Chat since not everyone from each team was able to make it to our last call. Please get in touch to schedule.

Please keep in touch on Slack and Twitter!

Cheers,

Anna & Julie

## Digest: Cohort Call 4 [ 2021-FDD ]

[CohortCalls folder](https://drive.google.com/drive/folders/1Xx-G_9s6DGz4JduYQblJNuMMFaPgU7sb?usp=sharing) - contains video recordings and completed agendas
[openscapes.github.io/2021-fdd](https://openscapes.github.io/2021-fdd) - Cohort webpage

**Goals:** Each team shared their pathway and we discussed how to keep momentum going forward.

**Themes** that came across through the final pathways shares:

- Lots of interest in investing time to developing documentation of onboarding/offboarding processes, codes of conduct, available datasets/data description guides, methodologies.
- There are challenges around if/how to share confidential data, or other people's data - and interest in continuing dialogue within the FDD community to find solutions.
- Collaboration is essential within teams and with external partners, but finding the right workflows and tools to do that well takes time and iteration. We're working on it! 
- Lots of actions and next steps, including increasing or refining use of GitHub (or other collaboration tools) in workflows, and continuing bi-weekly FDD Cohort calls, and alternating between share outs, co-working, office hours, etc. 

**Resources:**

- [PathwayShare Folder](https://drive.google.com/drive/u/2/folders/1j1nYc_FPgsfCm9XvLWvQBdcsCMZczHd8)
- Slide decks from past calls are available publicly from [openscapes.org/series](https://openscapes.github.io/series)
- “Graduation gift” - Openscapes badges by Allison Horst!
    * Download from here: [openscapes_hex_badge.png](https://github.com/Openscapes/how_we_work/blob/main/openscapes_hex_badge.png)
    * You can put it on your website, like the [Wood Lab](https://chelsealwood.com/research/) and the [Fay Lab](https://thefaylab.github.io/lab-manual/index.html)!

**A few lines from shared notes in the Agenda doc:**

- Thought a lot about code of conduct; need to be more clear about how to work with data, data access, acknowledging contributors across multiple institutions +1 +1 +1
- +1 to [Gavin’s onboarding document](https://thefaylab.github.io/lab-manual/index.html)
    * Julie ‘made’ us use a Creative Commons license for the lab manual so it’s there for stealing and modifying. Go nuts!
- How to not create a divide between GH/R/diff data users and non +1 +1 +1
- FDD Office Hours +1 +1 +1 +1 +1
    * Or co-working, or share outs
    * Keeping every 2 weeks timing - alternating co-working and more planned content (share your research using FDD to start)
    * Have space that allows for conversation of how these tools are actually used to do science. Continuing conversations about how we work is very valuable.

**Comment by AHolder1** [comment]
Hi @jules32 ! 

I have drafted the Digest for Call 4 using the template and the [CSS Call 4 Digest](https://github.com/Openscapes/css-cohort/issues/19) as an example. Please take a look and revise as desired. 

Thanks - have a great weekend! :)

**Comment by jules32** [comment]
@AHolder1 ! You are the best, thank you! This is really great, I can fill in from here. Thanks again for an awesome day!

**Comment by jules32** [comment]
Thanks again! Posted here: https://github.com/Openscapes/2021-fdd/issues/34
