### ISSUE TITLE
2022-afsc talk & sign-up sheet for Dec 2

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#39]
Hi @Openscapes/2022-afsc-assist !

I've tidied up the [planning doc timeline](https://docs.google.com/document/d/1VUefN2fQftRArPQG9Gr3CBimZW2Kz-fvO37tExe7q_s/edit#) and wanted to highlight the following TODO's: 

- [x] sign-up sheet - Em, Megsie, Josh
- [x] 10-15 min talk - Julie

If you need any announcement text, there is language in the planning doc and I can help more too!

**Comment by MargaretSiple-NOAA** [comment]
I drafted a sign-up form [here ](https://docs.google.com/forms/d/13XkWfyOrlzuJJprwIN2ahysZJGv6VAo390asEwHq0b0/edit)and a email announcement [here](https://docs.google.com/document/d/1gndDIl_fbAtXNdChv32oxwNbmtGbxiDjFUnXkqyQBHA/edit?usp=sharing) ! LMK what you think of them and I'll check off the 'sign-up sheet' box when we are satisfied.

**Comment by MargaretSiple-NOAA** [comment]
Talk and sign-up sheet are done!
