### ISSUE TITLE
pre-cohort setup [ 2022-nmfs-afsc ]

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#48]
This issue is to help track the pre-cohort setup, following the [approach-guide](https://openscapes.github.io/approach-guide/champions/) and focused on the engagement and tech setup after participants have been selected.

These TODO's are for @jules32 unless otherwise noted. cc: @Openscapes/2022-noaa-afsc-assist 

## For Cohort Planning Team 

- [x] invite co-leads/assists to Google Calendar Cohort Calls
- [x] create GitHub Team with co-leads/assists 
- [x] create Quicklinks issue and pin, tag assists team
- [x] create planning Google Folder: `Engage-2022-AFSC` (should rename this for consistency)
- [x] add co-leads/assists to Google Folder
- [x] setup Planning Doc
- [x] for Seaside Chats doc, add co-leads/assists

## For Participants

- [x] create Google Folder: `Openscapes_CohortCalls [ 2021-noaa-afsc ]` 
- [x] add participants emails to `Openscapes_CohortCalls [ 2021-noaa-afsc ]` - Do this the day before Cohort Call 1
- [x] add participants emails to Google Calendar Invites: Cohort Calls
- [x] add participants emails to Google Calendar Invites: Co-working times (optional) (experiment, previously have added those times week-to-week)
- [x] draft welcome email
- [x] send welcome email
- [x] send "reminder" email 1 day before, after adding participants to `Openscapes_CohortCalls [ 2021-noaa-afsc ]`
- [x] create GitHub repo - upcoming, testing `kyber` package for automation

**Comment by jules32** [comment]
Sent the email and added folks to the cohort folder!

**Comment by EmilyMarkowitz-NOAA** [comment]
- [ ] Em - add all participants to the 'Openscapes AFSC 2022 Cohort' google space

**Comment by jules32** [comment]
woop we're all set! here is the cohort page: https://openscapes.github.io/2022-noaa-afsc/ 

@Openscapes/2022-noaa-afsc-assist I'll be in the Zoom room 20 mins ahead of time if you'd like to/are able to join (no obligation!)
