### ISSUE TITLE
After Cohort Call 1: - Stef leads - Engagement

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#72]
TODO - asynchronously:
 
- [x] Field Notes
- [x] send a Digest (1st time is via email, afterwards is via GH issues)
- [x] Slack invites
- [x] Coworking calendar invites

**Comment by stefaniebutland** [comment]
thinking ahead, in the checklist, good to link to example Field Notes & Digest

**Comment by jules32** [comment]
Yes - Field Notes are described (but no examples yet) and Digest examples are found here: https://openscapes.github.io/approach-guide/champions/leading-cohort-calls.html#between-cohort-calls.

**Comment by stefaniebutland** [comment]
completed!

**Comment by stefaniebutland** [comment]
Note to selves: include Slack orientation and invitation link in Digest #1 email.
