### ISSUE TITLE
Before Cohort Call 2 - Coworking - Tech setup

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#73]
- [x] Before Cohort Call 2 - Coworking - effective to talk it out together 
- [x] Kyber setup (GitHub Clinic)
- [x] Create Agenda (kyber)
- [x] Review roles and timing

**Comment by stefaniebutland** [comment]
Notes we followed to create Call 2 Agenda: https://github.com/Openscapes/kyber/issues/9.

Stef had to execute a thing to authorize use of gargle (googlesheets stuff). Julie had commands in an issue.

**Comment by stefaniebutland** [comment]
Julie updated kyber docs while Stef drove the bus. Worked great!
