### ISSUE TITLE
Invite Assists & Guest Teachers

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#76]
- [x] Invite Assists: PIFSC, SWFSC 
- [x] Identify Guest Teachers: Ady, FayLab
- [x] Invite Guest Teachers

**Comment by jules32** [comment]
I've invited Angelia to guest teach either Data Strategies or Coding Strategies (Calls 3 or 4), she'll let us know availability Monday

**Comment by jules32** [comment]
@stefaniebutland to invite Amanda, Kevin, Juliette to attend Call 4 or 5, give them the option or either date or both, so they can get a feel for what cohort calls are

**Comment by stefaniebutland** [comment]
emailed Jul 14. Did not cc Julie. Won't close the issue till we have responses.

**Comment by stefaniebutland** [comment]
Kevin attending Aug 11. Sent cal invite.
