### ISSUE TITLE
Approach Guide review

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#79]
Following Cohort Call 1, @stefaniebutland will you review the relevant chapters in the Approach Guide - Champions section to identify & fill any gaps? This can be something to do following each Cohort Call: with your fresh eyes, what did you see setup that wasn't documented, how would any reordering help, what could be clarified? With an eye towards taking more of a pre-cohort engagement/tech lead in the Fall :)

**Comment by stefaniebutland** [comment]
For this phase, everything is either updated, in [this PR](https://github.com/Openscapes/approach-guide/pull/36), or in [an Issue](https://github.com/Openscapes/approach-guide/issues)

**Comment by stefaniebutland** [comment]
Current focus of Approach Guide review & updates is to enable NASA Mentors to use it. Cohort-planning GitHub Issue templates can link to sections of Approach Guide for how-to's.
