### ISSUE TITLE
Approach Guide: see comments Jamming & games for planning & team building

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/cohort-planning#81]
An idea from Eli Holmes.

Example, use Google Jamboard to have people experience how they might contribute to a team project.

**Comment by stefaniebutland** [comment]
We used Jamboard successfully in Mentors Seaside Chat early August and with ~30 people in SEFSC Cohort in 3 breakout rooms with 3 Jamboards to help people think about their Pathways

**Comment by stefaniebutland** [comment]
And we used it in 2022-sefsc-summer Cohort Call 4. 
@jules32 shall I add the Jamboard script and tips from Call 4 Agenda to Lesson Series? In which section?

**Comment by jules32** [comment]
How about at the top of the intro section of https://openscapes.github.io/approach-guide/champions/leading-cohort-calls.html. Something like "we also experiment ideas and incorporate them into subsequent calls within a cohort as needed. For example, we experimented with jamboards in summer, and then in fall updated the "am I doing openscapes right" and will be providing more pathways support in the future"

**Comment by stefaniebutland** [comment]
addressed in PR https://github.com/Openscapes/approach-guide/pull/63
