### ISSUE TITLE
Digest 1 & additional setup [ 2022-noaa-nwfsc-fall ]

### ISSUE THREAD

**Issue by jules32** [Openscapes/cohort-planning#96]
- [x] Field Notes

- [x] Digest 1, via email (include Slack invite & orientation, below), then post as issue in Cohort repo
  - [examples in Approach Guide](https://openscapes.github.io/approach-guide/champions/leading-cohort-calls.html#between-cohort-calls)

-   [x] Slack
    -   [x] (create private cohort channel - for Fall NMFS we'll have one Slack channel for all 4 Cohorts)
    - [x] Email participants link to join Slack, with orientation to Slack e.g. how to, #welcome channel, etc 

-   [x] Google Calendar
    -   [x] add participants emails to Google Calendar Invites: Co-working times (participation optional)

**Comment by stefaniebutland** [comment]
note we reached a Google Cal limit - could not add NWFSC or AFSC emails to cross-cohort coworking. Added as supplemental info to Digest and post to Google Space
